-- Manual PostgreSQL SQL for Brand Partners
-- Run manually; do not use Laravel migrations.

CREATE TABLE IF NOT EXISTS brand_partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    logo VARCHAR(255) NULL,
    cover_image VARCHAR(255) NULL,
    short_description VARCHAR(500) NULL,
    description TEXT NULL,
    category_id UUID NULL,
    website VARCHAR(255) NULL,
    contact_email VARCHAR(255) NULL,
    contact_number VARCHAR(50) NULL,
    whatsapp VARCHAR(50) NULL,
    address VARCHAR(500) NULL,
    offer_title VARCHAR(255) NULL,
    offer_description TEXT NULL,
    coupon_code VARCHAR(100) NULL,
    discount_type VARCHAR(50) NULL,
    discount_value NUMERIC(12,2) NULL,
    valid_from TIMESTAMPTZ NULL,
    valid_to TIMESTAMPTZ NULL,
    terms_and_conditions TEXT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_sponsored BOOLEAN NOT NULL DEFAULT FALSE,
    meta_title VARCHAR(255) NULL,
    meta_description VARCHAR(500) NULL,
    keywords VARCHAR(255) NULL,
    created_by UUID NULL,
    updated_by UUID NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NULL,
    CONSTRAINT uq_brand_partners_slug UNIQUE (slug),
    CONSTRAINT uq_brand_partners_uuid UNIQUE (uuid)
);
